# Generated by Django 4.2.5 on 2023-09-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
