# Generated by Django 4.2.5 on 2023-09-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('name',)},
        ),
    ]
