# Generated by Django 4.2.5 on 2023-09-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_size_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
