# Generated by Django 4.2.5 on 2023-09-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
    ]
