# Generated by Django 4.2.5 on 2023-09-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='default',
        ),
    ]
